namespace Rena.Interop.OpenGL;

public unsafe partial class GLES1
{
    internal static ReadOnlySpan<byte> glAlphaFuncFunctionName => "glAlphaFunc"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> glAlphaFunc;
    internal static ReadOnlySpan<byte> glClearColorFunctionName => "glClearColor"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glClearColor;
    internal static ReadOnlySpan<byte> glClearDepthfFunctionName => "glClearDepthf"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glClearDepthf;
    internal static ReadOnlySpan<byte> glClipPlanefFunctionName => "glClipPlanef"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glClipPlanef;
    internal static ReadOnlySpan<byte> glColor4fFunctionName => "glColor4f"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glColor4f;
    internal static ReadOnlySpan<byte> glDepthRangefFunctionName => "glDepthRangef"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> glDepthRangef;
    internal static ReadOnlySpan<byte> glFogfFunctionName => "glFogf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> glFogf;
    internal static ReadOnlySpan<byte> glFogfvFunctionName => "glFogfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glFogfv;
    internal static ReadOnlySpan<byte> glFrustumfFunctionName => "glFrustumf"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glFrustumf;
    internal static ReadOnlySpan<byte> glGetClipPlanefFunctionName => "glGetClipPlanef"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetClipPlanef;
    internal static ReadOnlySpan<byte> glGetFloatvFunctionName => "glGetFloatv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetFloatv;
    internal static ReadOnlySpan<byte> glGetLightfvFunctionName => "glGetLightfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetLightfv;
    internal static ReadOnlySpan<byte> glGetMaterialfvFunctionName => "glGetMaterialfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetMaterialfv;
    internal static ReadOnlySpan<byte> glGetTexEnvfvFunctionName => "glGetTexEnvfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetTexEnvfv;
    internal static ReadOnlySpan<byte> glGetTexParameterfvFunctionName => "glGetTexParameterfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetTexParameterfv;
    internal static ReadOnlySpan<byte> glLightModelfFunctionName => "glLightModelf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> glLightModelf;
    internal static ReadOnlySpan<byte> glLightModelfvFunctionName => "glLightModelfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glLightModelfv;
    internal static ReadOnlySpan<byte> glLightfFunctionName => "glLightf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glLightf;
    internal static ReadOnlySpan<byte> glLightfvFunctionName => "glLightfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glLightfv;
    internal static ReadOnlySpan<byte> glLineWidthFunctionName => "glLineWidth"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glLineWidth;
    internal static ReadOnlySpan<byte> glLoadMatrixfFunctionName => "glLoadMatrixf"u8;
    private readonly delegate* unmanaged</* GLfloat */ float*, /* void */ void> glLoadMatrixf;
    internal static ReadOnlySpan<byte> glMaterialfFunctionName => "glMaterialf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glMaterialf;
    internal static ReadOnlySpan<byte> glMaterialfvFunctionName => "glMaterialfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glMaterialfv;
    internal static ReadOnlySpan<byte> glMultMatrixfFunctionName => "glMultMatrixf"u8;
    private readonly delegate* unmanaged</* GLfloat */ float*, /* void */ void> glMultMatrixf;
    internal static ReadOnlySpan<byte> glMultiTexCoord4fFunctionName => "glMultiTexCoord4f"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glMultiTexCoord4f;
    internal static ReadOnlySpan<byte> glNormal3fFunctionName => "glNormal3f"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glNormal3f;
    internal static ReadOnlySpan<byte> glOrthofFunctionName => "glOrthof"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glOrthof;
    internal static ReadOnlySpan<byte> glPointParameterfFunctionName => "glPointParameterf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> glPointParameterf;
    internal static ReadOnlySpan<byte> glPointParameterfvFunctionName => "glPointParameterfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glPointParameterfv;
    internal static ReadOnlySpan<byte> glPointSizeFunctionName => "glPointSize"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glPointSize;
    internal static ReadOnlySpan<byte> glPolygonOffsetFunctionName => "glPolygonOffset"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> glPolygonOffset;
    internal static ReadOnlySpan<byte> glRotatefFunctionName => "glRotatef"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glRotatef;
    internal static ReadOnlySpan<byte> glScalefFunctionName => "glScalef"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glScalef;
    internal static ReadOnlySpan<byte> glTexEnvfFunctionName => "glTexEnvf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glTexEnvf;
    internal static ReadOnlySpan<byte> glTexEnvfvFunctionName => "glTexEnvfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glTexEnvfv;
    internal static ReadOnlySpan<byte> glTexParameterfFunctionName => "glTexParameterf"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glTexParameterf;
    internal static ReadOnlySpan<byte> glTexParameterfvFunctionName => "glTexParameterfv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glTexParameterfv;
    internal static ReadOnlySpan<byte> glTranslatefFunctionName => "glTranslatef"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glTranslatef;
    internal static ReadOnlySpan<byte> glActiveTextureFunctionName => "glActiveTexture"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glActiveTexture;
    internal static ReadOnlySpan<byte> glAlphaFuncxFunctionName => "glAlphaFuncx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> glAlphaFuncx;
    internal static ReadOnlySpan<byte> glBindBufferFunctionName => "glBindBuffer"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindBuffer;
    internal static ReadOnlySpan<byte> glBindTextureFunctionName => "glBindTexture"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindTexture;
    internal static ReadOnlySpan<byte> glBlendFuncFunctionName => "glBlendFunc"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendFunc;
    internal static ReadOnlySpan<byte> glBufferDataFunctionName => "glBufferData"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizeiptr */ nint, /* void */ void*, /* GLenum */ int, /* void */ void> glBufferData;
    internal static ReadOnlySpan<byte> glBufferSubDataFunctionName => "glBufferSubData"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void*, /* void */ void> glBufferSubData;
    internal static ReadOnlySpan<byte> glClearFunctionName => "glClear"u8;
    private readonly delegate* unmanaged</* GLbitfield */ int, /* void */ void> glClear;
    internal static ReadOnlySpan<byte> glClearColorxFunctionName => "glClearColorx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glClearColorx;
    internal static ReadOnlySpan<byte> glClearDepthxFunctionName => "glClearDepthx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> glClearDepthx;
    internal static ReadOnlySpan<byte> glClearStencilFunctionName => "glClearStencil"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* void */ void> glClearStencil;
    internal static ReadOnlySpan<byte> glClientActiveTextureFunctionName => "glClientActiveTexture"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glClientActiveTexture;
    internal static ReadOnlySpan<byte> glClipPlanexFunctionName => "glClipPlanex"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glClipPlanex;
    internal static ReadOnlySpan<byte> glColor4ubFunctionName => "glColor4ub"u8;
    private readonly delegate* unmanaged</* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* void */ void> glColor4ub;
    internal static ReadOnlySpan<byte> glColor4xFunctionName => "glColor4x"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glColor4x;
    internal static ReadOnlySpan<byte> glColorMaskFunctionName => "glColorMask"u8;
    private readonly delegate* unmanaged</* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* void */ void> glColorMask;
    internal static ReadOnlySpan<byte> glColorPointerFunctionName => "glColorPointer"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glColorPointer;
    internal static ReadOnlySpan<byte> glCompressedTexImage2DFunctionName => "glCompressedTexImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexImage2D;
    internal static ReadOnlySpan<byte> glCompressedTexSubImage2DFunctionName => "glCompressedTexSubImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexSubImage2D;
    internal static ReadOnlySpan<byte> glCopyTexImage2DFunctionName => "glCopyTexImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* void */ void> glCopyTexImage2D;
    internal static ReadOnlySpan<byte> glCopyTexSubImage2DFunctionName => "glCopyTexSubImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glCopyTexSubImage2D;
    internal static ReadOnlySpan<byte> glCullFaceFunctionName => "glCullFace"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glCullFace;
    internal static ReadOnlySpan<byte> glDeleteBuffersFunctionName => "glDeleteBuffers"u8;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteBuffers;
    internal static ReadOnlySpan<byte> glDeleteTexturesFunctionName => "glDeleteTextures"u8;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteTextures;
    internal static ReadOnlySpan<byte> glDepthFuncFunctionName => "glDepthFunc"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glDepthFunc;
    internal static ReadOnlySpan<byte> glDepthMaskFunctionName => "glDepthMask"u8;
    private readonly delegate* unmanaged</* GLboolean */ int, /* void */ void> glDepthMask;
    internal static ReadOnlySpan<byte> glDepthRangexFunctionName => "glDepthRangex"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glDepthRangex;
    internal static ReadOnlySpan<byte> glDisableFunctionName => "glDisable"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glDisable;
    internal static ReadOnlySpan<byte> glDisableClientStateFunctionName => "glDisableClientState"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glDisableClientState;
    internal static ReadOnlySpan<byte> glDrawArraysFunctionName => "glDrawArrays"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void> glDrawArrays;
    internal static ReadOnlySpan<byte> glDrawElementsFunctionName => "glDrawElements"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glDrawElements;
    internal static ReadOnlySpan<byte> glEnableFunctionName => "glEnable"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glEnable;
    internal static ReadOnlySpan<byte> glEnableClientStateFunctionName => "glEnableClientState"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glEnableClientState;
    internal static ReadOnlySpan<byte> glFinishFunctionName => "glFinish"u8;
    private readonly delegate* unmanaged</* void */ void> glFinish;
    internal static ReadOnlySpan<byte> glFlushFunctionName => "glFlush"u8;
    private readonly delegate* unmanaged</* void */ void> glFlush;
    internal static ReadOnlySpan<byte> glFogxFunctionName => "glFogx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> glFogx;
    internal static ReadOnlySpan<byte> glFogxvFunctionName => "glFogxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glFogxv;
    internal static ReadOnlySpan<byte> glFrontFaceFunctionName => "glFrontFace"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glFrontFace;
    internal static ReadOnlySpan<byte> glFrustumxFunctionName => "glFrustumx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glFrustumx;
    internal static ReadOnlySpan<byte> glGetBooleanvFunctionName => "glGetBooleanv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int*, /* void */ void> glGetBooleanv;
    internal static ReadOnlySpan<byte> glGetBufferParameterivFunctionName => "glGetBufferParameteriv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetBufferParameteriv;
    internal static ReadOnlySpan<byte> glGetClipPlanexFunctionName => "glGetClipPlanex"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetClipPlanex;
    internal static ReadOnlySpan<byte> glGenBuffersFunctionName => "glGenBuffers"u8;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenBuffers;
    internal static ReadOnlySpan<byte> glGenTexturesFunctionName => "glGenTextures"u8;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenTextures;
    internal static ReadOnlySpan<byte> glGetErrorFunctionName => "glGetError"u8;
    private readonly delegate* unmanaged</* GLenum */ int> glGetError;
    internal static ReadOnlySpan<byte> glGetFixedvFunctionName => "glGetFixedv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetFixedv;
    internal static ReadOnlySpan<byte> glGetIntegervFunctionName => "glGetIntegerv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int*, /* void */ void> glGetIntegerv;
    internal static ReadOnlySpan<byte> glGetLightxvFunctionName => "glGetLightxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetLightxv;
    internal static ReadOnlySpan<byte> glGetMaterialxvFunctionName => "glGetMaterialxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetMaterialxv;
    internal static ReadOnlySpan<byte> glGetPointervFunctionName => "glGetPointerv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void**, /* void */ void> glGetPointerv;
    internal static ReadOnlySpan<byte> glGetStringFunctionName => "glGetString"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLubyte */ byte*> glGetString;
    internal static ReadOnlySpan<byte> glGetTexEnvivFunctionName => "glGetTexEnviv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetTexEnviv;
    internal static ReadOnlySpan<byte> glGetTexEnvxvFunctionName => "glGetTexEnvxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetTexEnvxv;
    internal static ReadOnlySpan<byte> glGetTexParameterivFunctionName => "glGetTexParameteriv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetTexParameteriv;
    internal static ReadOnlySpan<byte> glGetTexParameterxvFunctionName => "glGetTexParameterxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glGetTexParameterxv;
    internal static ReadOnlySpan<byte> glHintFunctionName => "glHint"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> glHint;
    internal static ReadOnlySpan<byte> glIsBufferFunctionName => "glIsBuffer"u8;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsBuffer;
    internal static ReadOnlySpan<byte> glIsEnabledFunctionName => "glIsEnabled"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int> glIsEnabled;
    internal static ReadOnlySpan<byte> glIsTextureFunctionName => "glIsTexture"u8;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsTexture;
    internal static ReadOnlySpan<byte> glLightModelxFunctionName => "glLightModelx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> glLightModelx;
    internal static ReadOnlySpan<byte> glLightModelxvFunctionName => "glLightModelxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glLightModelxv;
    internal static ReadOnlySpan<byte> glLightxFunctionName => "glLightx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> glLightx;
    internal static ReadOnlySpan<byte> glLightxvFunctionName => "glLightxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glLightxv;
    internal static ReadOnlySpan<byte> glLineWidthxFunctionName => "glLineWidthx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> glLineWidthx;
    internal static ReadOnlySpan<byte> glLoadIdentityFunctionName => "glLoadIdentity"u8;
    private readonly delegate* unmanaged</* void */ void> glLoadIdentity;
    internal static ReadOnlySpan<byte> glLoadMatrixxFunctionName => "glLoadMatrixx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint*, /* void */ void> glLoadMatrixx;
    internal static ReadOnlySpan<byte> glLogicOpFunctionName => "glLogicOp"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glLogicOp;
    internal static ReadOnlySpan<byte> glMaterialxFunctionName => "glMaterialx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> glMaterialx;
    internal static ReadOnlySpan<byte> glMaterialxvFunctionName => "glMaterialxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glMaterialxv;
    internal static ReadOnlySpan<byte> glMatrixModeFunctionName => "glMatrixMode"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glMatrixMode;
    internal static ReadOnlySpan<byte> glMultMatrixxFunctionName => "glMultMatrixx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint*, /* void */ void> glMultMatrixx;
    internal static ReadOnlySpan<byte> glMultiTexCoord4xFunctionName => "glMultiTexCoord4x"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glMultiTexCoord4x;
    internal static ReadOnlySpan<byte> glNormal3xFunctionName => "glNormal3x"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glNormal3x;
    internal static ReadOnlySpan<byte> glNormalPointerFunctionName => "glNormalPointer"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glNormalPointer;
    internal static ReadOnlySpan<byte> glOrthoxFunctionName => "glOrthox"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glOrthox;
    internal static ReadOnlySpan<byte> glPixelStoreiFunctionName => "glPixelStorei"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* void */ void> glPixelStorei;
    internal static ReadOnlySpan<byte> glPointParameterxFunctionName => "glPointParameterx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> glPointParameterx;
    internal static ReadOnlySpan<byte> glPointParameterxvFunctionName => "glPointParameterxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glPointParameterxv;
    internal static ReadOnlySpan<byte> glPointSizexFunctionName => "glPointSizex"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> glPointSizex;
    internal static ReadOnlySpan<byte> glPolygonOffsetxFunctionName => "glPolygonOffsetx"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glPolygonOffsetx;
    internal static ReadOnlySpan<byte> glPopMatrixFunctionName => "glPopMatrix"u8;
    private readonly delegate* unmanaged</* void */ void> glPopMatrix;
    internal static ReadOnlySpan<byte> glPushMatrixFunctionName => "glPushMatrix"u8;
    private readonly delegate* unmanaged</* void */ void> glPushMatrix;
    internal static ReadOnlySpan<byte> glReadPixelsFunctionName => "glReadPixels"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glReadPixels;
    internal static ReadOnlySpan<byte> glRotatexFunctionName => "glRotatex"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glRotatex;
    internal static ReadOnlySpan<byte> glSampleCoverageFunctionName => "glSampleCoverage"u8;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLboolean */ int, /* void */ void> glSampleCoverage;
    internal static ReadOnlySpan<byte> glSampleCoveragexFunctionName => "glSampleCoveragex"u8;
    private readonly delegate* unmanaged</* GLclampx */ int, /* GLboolean */ int, /* void */ void> glSampleCoveragex;
    internal static ReadOnlySpan<byte> glScalexFunctionName => "glScalex"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glScalex;
    internal static ReadOnlySpan<byte> glScissorFunctionName => "glScissor"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glScissor;
    internal static ReadOnlySpan<byte> glShadeModelFunctionName => "glShadeModel"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glShadeModel;
    internal static ReadOnlySpan<byte> glStencilFuncFunctionName => "glStencilFunc"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLuint */ uint, /* void */ void> glStencilFunc;
    internal static ReadOnlySpan<byte> glStencilMaskFunctionName => "glStencilMask"u8;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glStencilMask;
    internal static ReadOnlySpan<byte> glStencilOpFunctionName => "glStencilOp"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glStencilOp;
    internal static ReadOnlySpan<byte> glTexCoordPointerFunctionName => "glTexCoordPointer"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glTexCoordPointer;
    internal static ReadOnlySpan<byte> glTexEnviFunctionName => "glTexEnvi"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> glTexEnvi;
    internal static ReadOnlySpan<byte> glTexEnvxFunctionName => "glTexEnvx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> glTexEnvx;
    internal static ReadOnlySpan<byte> glTexEnvivFunctionName => "glTexEnviv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glTexEnviv;
    internal static ReadOnlySpan<byte> glTexEnvxvFunctionName => "glTexEnvxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glTexEnvxv;
    internal static ReadOnlySpan<byte> glTexImage2DFunctionName => "glTexImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexImage2D;
    internal static ReadOnlySpan<byte> glTexParameteriFunctionName => "glTexParameteri"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> glTexParameteri;
    internal static ReadOnlySpan<byte> glTexParameterxFunctionName => "glTexParameterx"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> glTexParameterx;
    internal static ReadOnlySpan<byte> glTexParameterivFunctionName => "glTexParameteriv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glTexParameteriv;
    internal static ReadOnlySpan<byte> glTexParameterxvFunctionName => "glTexParameterxv"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> glTexParameterxv;
    internal static ReadOnlySpan<byte> glTexSubImage2DFunctionName => "glTexSubImage2D"u8;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexSubImage2D;
    internal static ReadOnlySpan<byte> glTranslatexFunctionName => "glTranslatex"u8;
    private readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> glTranslatex;
    internal static ReadOnlySpan<byte> glVertexPointerFunctionName => "glVertexPointer"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glVertexPointer;
    internal static ReadOnlySpan<byte> glViewportFunctionName => "glViewport"u8;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glViewport;
}
