namespace Rena.Interop.OpenGL;

public unsafe partial class GLES1
{
    internal static ReadOnlySpan<byte> glAlphaFuncFunctionName => "glAlphaFunc"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> AlphaFunc;
    internal static ReadOnlySpan<byte> glClearColorFunctionName => "glClearColor"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> ClearColor;
    internal static ReadOnlySpan<byte> glClearDepthfFunctionName => "glClearDepthf"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> ClearDepthf;
    internal static ReadOnlySpan<byte> glClipPlanefFunctionName => "glClipPlanef"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> ClipPlanef;
    internal static ReadOnlySpan<byte> glColor4fFunctionName => "glColor4f"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Color4f;
    internal static ReadOnlySpan<byte> glDepthRangefFunctionName => "glDepthRangef"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> DepthRangef;
    internal static ReadOnlySpan<byte> glFogfFunctionName => "glFogf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> Fogf;
    internal static ReadOnlySpan<byte> glFogfvFunctionName => "glFogfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> Fogfv;
    internal static ReadOnlySpan<byte> glFrustumfFunctionName => "glFrustumf"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Frustumf;
    internal static ReadOnlySpan<byte> glGetClipPlanefFunctionName => "glGetClipPlanef"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetClipPlanef;
    internal static ReadOnlySpan<byte> glGetFloatvFunctionName => "glGetFloatv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetFloatv;
    internal static ReadOnlySpan<byte> glGetLightfvFunctionName => "glGetLightfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetLightfv;
    internal static ReadOnlySpan<byte> glGetMaterialfvFunctionName => "glGetMaterialfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetMaterialfv;
    internal static ReadOnlySpan<byte> glGetTexEnvfvFunctionName => "glGetTexEnvfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetTexEnvfv;
    internal static ReadOnlySpan<byte> glGetTexParameterfvFunctionName => "glGetTexParameterfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> GetTexParameterfv;
    internal static ReadOnlySpan<byte> glLightModelfFunctionName => "glLightModelf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> LightModelf;
    internal static ReadOnlySpan<byte> glLightModelfvFunctionName => "glLightModelfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> LightModelfv;
    internal static ReadOnlySpan<byte> glLightfFunctionName => "glLightf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> Lightf;
    internal static ReadOnlySpan<byte> glLightfvFunctionName => "glLightfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> Lightfv;
    internal static ReadOnlySpan<byte> glLineWidthFunctionName => "glLineWidth"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> LineWidth;
    internal static ReadOnlySpan<byte> glLoadMatrixfFunctionName => "glLoadMatrixf"u8;
    public readonly delegate* unmanaged</* GLfloat */ float*, /* void */ void> LoadMatrixf;
    internal static ReadOnlySpan<byte> glMaterialfFunctionName => "glMaterialf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> Materialf;
    internal static ReadOnlySpan<byte> glMaterialfvFunctionName => "glMaterialfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> Materialfv;
    internal static ReadOnlySpan<byte> glMultMatrixfFunctionName => "glMultMatrixf"u8;
    public readonly delegate* unmanaged</* GLfloat */ float*, /* void */ void> MultMatrixf;
    internal static ReadOnlySpan<byte> glMultiTexCoord4fFunctionName => "glMultiTexCoord4f"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> MultiTexCoord4f;
    internal static ReadOnlySpan<byte> glNormal3fFunctionName => "glNormal3f"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Normal3f;
    internal static ReadOnlySpan<byte> glOrthofFunctionName => "glOrthof"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Orthof;
    internal static ReadOnlySpan<byte> glPointParameterfFunctionName => "glPointParameterf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void> PointParameterf;
    internal static ReadOnlySpan<byte> glPointParameterfvFunctionName => "glPointParameterfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> PointParameterfv;
    internal static ReadOnlySpan<byte> glPointSizeFunctionName => "glPointSize"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> PointSize;
    internal static ReadOnlySpan<byte> glPolygonOffsetFunctionName => "glPolygonOffset"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> PolygonOffset;
    internal static ReadOnlySpan<byte> glRotatefFunctionName => "glRotatef"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Rotatef;
    internal static ReadOnlySpan<byte> glScalefFunctionName => "glScalef"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Scalef;
    internal static ReadOnlySpan<byte> glTexEnvfFunctionName => "glTexEnvf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> TexEnvf;
    internal static ReadOnlySpan<byte> glTexEnvfvFunctionName => "glTexEnvfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> TexEnvfv;
    internal static ReadOnlySpan<byte> glTexParameterfFunctionName => "glTexParameterf"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> TexParameterf;
    internal static ReadOnlySpan<byte> glTexParameterfvFunctionName => "glTexParameterfv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> TexParameterfv;
    internal static ReadOnlySpan<byte> glTranslatefFunctionName => "glTranslatef"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> Translatef;
    internal static ReadOnlySpan<byte> glActiveTextureFunctionName => "glActiveTexture"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> ActiveTexture;
    internal static ReadOnlySpan<byte> glAlphaFuncxFunctionName => "glAlphaFuncx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> AlphaFuncx;
    internal static ReadOnlySpan<byte> glBindBufferFunctionName => "glBindBuffer"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> BindBuffer;
    internal static ReadOnlySpan<byte> glBindTextureFunctionName => "glBindTexture"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> BindTexture;
    internal static ReadOnlySpan<byte> glBlendFuncFunctionName => "glBlendFunc"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> BlendFunc;
    internal static ReadOnlySpan<byte> glBufferDataFunctionName => "glBufferData"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLsizeiptr */ nint, /* void */ void*, /* GLenum */ int, /* void */ void> BufferData;
    internal static ReadOnlySpan<byte> glBufferSubDataFunctionName => "glBufferSubData"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void*, /* void */ void> BufferSubData;
    internal static ReadOnlySpan<byte> glClearFunctionName => "glClear"u8;
    public readonly delegate* unmanaged</* GLbitfield */ int, /* void */ void> Clear;
    internal static ReadOnlySpan<byte> glClearColorxFunctionName => "glClearColorx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> ClearColorx;
    internal static ReadOnlySpan<byte> glClearDepthxFunctionName => "glClearDepthx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> ClearDepthx;
    internal static ReadOnlySpan<byte> glClearStencilFunctionName => "glClearStencil"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* void */ void> ClearStencil;
    internal static ReadOnlySpan<byte> glClientActiveTextureFunctionName => "glClientActiveTexture"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> ClientActiveTexture;
    internal static ReadOnlySpan<byte> glClipPlanexFunctionName => "glClipPlanex"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> ClipPlanex;
    internal static ReadOnlySpan<byte> glColor4ubFunctionName => "glColor4ub"u8;
    public readonly delegate* unmanaged</* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* void */ void> Color4ub;
    internal static ReadOnlySpan<byte> glColor4xFunctionName => "glColor4x"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Color4x;
    internal static ReadOnlySpan<byte> glColorMaskFunctionName => "glColorMask"u8;
    public readonly delegate* unmanaged</* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* void */ void> ColorMask;
    internal static ReadOnlySpan<byte> glColorPointerFunctionName => "glColorPointer"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> ColorPointer;
    internal static ReadOnlySpan<byte> glCompressedTexImage2DFunctionName => "glCompressedTexImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> CompressedTexImage2D;
    internal static ReadOnlySpan<byte> glCompressedTexSubImage2DFunctionName => "glCompressedTexSubImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> CompressedTexSubImage2D;
    internal static ReadOnlySpan<byte> glCopyTexImage2DFunctionName => "glCopyTexImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* void */ void> CopyTexImage2D;
    internal static ReadOnlySpan<byte> glCopyTexSubImage2DFunctionName => "glCopyTexSubImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> CopyTexSubImage2D;
    internal static ReadOnlySpan<byte> glCullFaceFunctionName => "glCullFace"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> CullFace;
    internal static ReadOnlySpan<byte> glDeleteBuffersFunctionName => "glDeleteBuffers"u8;
    public readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> DeleteBuffers;
    internal static ReadOnlySpan<byte> glDeleteTexturesFunctionName => "glDeleteTextures"u8;
    public readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> DeleteTextures;
    internal static ReadOnlySpan<byte> glDepthFuncFunctionName => "glDepthFunc"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> DepthFunc;
    internal static ReadOnlySpan<byte> glDepthMaskFunctionName => "glDepthMask"u8;
    public readonly delegate* unmanaged</* GLboolean */ int, /* void */ void> DepthMask;
    internal static ReadOnlySpan<byte> glDepthRangexFunctionName => "glDepthRangex"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> DepthRangex;
    internal static ReadOnlySpan<byte> glDisableFunctionName => "glDisable"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> Disable;
    internal static ReadOnlySpan<byte> glDisableClientStateFunctionName => "glDisableClientState"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> DisableClientState;
    internal static ReadOnlySpan<byte> glDrawArraysFunctionName => "glDrawArrays"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void> DrawArrays;
    internal static ReadOnlySpan<byte> glDrawElementsFunctionName => "glDrawElements"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* void */ void> DrawElements;
    internal static ReadOnlySpan<byte> glEnableFunctionName => "glEnable"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> Enable;
    internal static ReadOnlySpan<byte> glEnableClientStateFunctionName => "glEnableClientState"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> EnableClientState;
    internal static ReadOnlySpan<byte> glFinishFunctionName => "glFinish"u8;
    public readonly delegate* unmanaged</* void */ void> Finish;
    internal static ReadOnlySpan<byte> glFlushFunctionName => "glFlush"u8;
    public readonly delegate* unmanaged</* void */ void> Flush;
    internal static ReadOnlySpan<byte> glFogxFunctionName => "glFogx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> Fogx;
    internal static ReadOnlySpan<byte> glFogxvFunctionName => "glFogxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> Fogxv;
    internal static ReadOnlySpan<byte> glFrontFaceFunctionName => "glFrontFace"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> FrontFace;
    internal static ReadOnlySpan<byte> glFrustumxFunctionName => "glFrustumx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Frustumx;
    internal static ReadOnlySpan<byte> glGetBooleanvFunctionName => "glGetBooleanv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int*, /* void */ void> GetBooleanv;
    internal static ReadOnlySpan<byte> glGetBufferParameterivFunctionName => "glGetBufferParameteriv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> GetBufferParameteriv;
    internal static ReadOnlySpan<byte> glGetClipPlanexFunctionName => "glGetClipPlanex"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetClipPlanex;
    internal static ReadOnlySpan<byte> glGenBuffersFunctionName => "glGenBuffers"u8;
    public readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> GenBuffers;
    internal static ReadOnlySpan<byte> glGenTexturesFunctionName => "glGenTextures"u8;
    public readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> GenTextures;
    internal static ReadOnlySpan<byte> glGetErrorFunctionName => "glGetError"u8;
    public readonly delegate* unmanaged</* GLenum */ int> GetError;
    internal static ReadOnlySpan<byte> glGetFixedvFunctionName => "glGetFixedv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetFixedv;
    internal static ReadOnlySpan<byte> glGetIntegervFunctionName => "glGetIntegerv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int*, /* void */ void> GetIntegerv;
    internal static ReadOnlySpan<byte> glGetLightxvFunctionName => "glGetLightxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetLightxv;
    internal static ReadOnlySpan<byte> glGetMaterialxvFunctionName => "glGetMaterialxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetMaterialxv;
    internal static ReadOnlySpan<byte> glGetPointervFunctionName => "glGetPointerv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void**, /* void */ void> GetPointerv;
    internal static ReadOnlySpan<byte> glGetStringFunctionName => "glGetString"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLubyte */ byte*> GetString;
    internal static ReadOnlySpan<byte> glGetTexEnvivFunctionName => "glGetTexEnviv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> GetTexEnviv;
    internal static ReadOnlySpan<byte> glGetTexEnvxvFunctionName => "glGetTexEnvxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetTexEnvxv;
    internal static ReadOnlySpan<byte> glGetTexParameterivFunctionName => "glGetTexParameteriv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> GetTexParameteriv;
    internal static ReadOnlySpan<byte> glGetTexParameterxvFunctionName => "glGetTexParameterxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> GetTexParameterxv;
    internal static ReadOnlySpan<byte> glHintFunctionName => "glHint"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> Hint;
    internal static ReadOnlySpan<byte> glIsBufferFunctionName => "glIsBuffer"u8;
    public readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> IsBuffer;
    internal static ReadOnlySpan<byte> glIsEnabledFunctionName => "glIsEnabled"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int> IsEnabled;
    internal static ReadOnlySpan<byte> glIsTextureFunctionName => "glIsTexture"u8;
    public readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> IsTexture;
    internal static ReadOnlySpan<byte> glLightModelxFunctionName => "glLightModelx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> LightModelx;
    internal static ReadOnlySpan<byte> glLightModelxvFunctionName => "glLightModelxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> LightModelxv;
    internal static ReadOnlySpan<byte> glLightxFunctionName => "glLightx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> Lightx;
    internal static ReadOnlySpan<byte> glLightxvFunctionName => "glLightxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> Lightxv;
    internal static ReadOnlySpan<byte> glLineWidthxFunctionName => "glLineWidthx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> LineWidthx;
    internal static ReadOnlySpan<byte> glLoadIdentityFunctionName => "glLoadIdentity"u8;
    public readonly delegate* unmanaged</* void */ void> LoadIdentity;
    internal static ReadOnlySpan<byte> glLoadMatrixxFunctionName => "glLoadMatrixx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint*, /* void */ void> LoadMatrixx;
    internal static ReadOnlySpan<byte> glLogicOpFunctionName => "glLogicOp"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> LogicOp;
    internal static ReadOnlySpan<byte> glMaterialxFunctionName => "glMaterialx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> Materialx;
    internal static ReadOnlySpan<byte> glMaterialxvFunctionName => "glMaterialxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> Materialxv;
    internal static ReadOnlySpan<byte> glMatrixModeFunctionName => "glMatrixMode"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> MatrixMode;
    internal static ReadOnlySpan<byte> glMultMatrixxFunctionName => "glMultMatrixx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint*, /* void */ void> MultMatrixx;
    internal static ReadOnlySpan<byte> glMultiTexCoord4xFunctionName => "glMultiTexCoord4x"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> MultiTexCoord4x;
    internal static ReadOnlySpan<byte> glNormal3xFunctionName => "glNormal3x"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Normal3x;
    internal static ReadOnlySpan<byte> glNormalPointerFunctionName => "glNormalPointer"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> NormalPointer;
    internal static ReadOnlySpan<byte> glOrthoxFunctionName => "glOrthox"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Orthox;
    internal static ReadOnlySpan<byte> glPixelStoreiFunctionName => "glPixelStorei"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* void */ void> PixelStorei;
    internal static ReadOnlySpan<byte> glPointParameterxFunctionName => "glPointParameterx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void> PointParameterx;
    internal static ReadOnlySpan<byte> glPointParameterxvFunctionName => "glPointParameterxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void> PointParameterxv;
    internal static ReadOnlySpan<byte> glPointSizexFunctionName => "glPointSizex"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* void */ void> PointSizex;
    internal static ReadOnlySpan<byte> glPolygonOffsetxFunctionName => "glPolygonOffsetx"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> PolygonOffsetx;
    internal static ReadOnlySpan<byte> glPopMatrixFunctionName => "glPopMatrix"u8;
    public readonly delegate* unmanaged</* void */ void> PopMatrix;
    internal static ReadOnlySpan<byte> glPushMatrixFunctionName => "glPushMatrix"u8;
    public readonly delegate* unmanaged</* void */ void> PushMatrix;
    internal static ReadOnlySpan<byte> glReadPixelsFunctionName => "glReadPixels"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> ReadPixels;
    internal static ReadOnlySpan<byte> glRotatexFunctionName => "glRotatex"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Rotatex;
    internal static ReadOnlySpan<byte> glSampleCoverageFunctionName => "glSampleCoverage"u8;
    public readonly delegate* unmanaged</* GLfloat */ float, /* GLboolean */ int, /* void */ void> SampleCoverage;
    internal static ReadOnlySpan<byte> glSampleCoveragexFunctionName => "glSampleCoveragex"u8;
    public readonly delegate* unmanaged</* GLclampx */ int, /* GLboolean */ int, /* void */ void> SampleCoveragex;
    internal static ReadOnlySpan<byte> glScalexFunctionName => "glScalex"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Scalex;
    internal static ReadOnlySpan<byte> glScissorFunctionName => "glScissor"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> Scissor;
    internal static ReadOnlySpan<byte> glShadeModelFunctionName => "glShadeModel"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* void */ void> ShadeModel;
    internal static ReadOnlySpan<byte> glStencilFuncFunctionName => "glStencilFunc"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLuint */ uint, /* void */ void> StencilFunc;
    internal static ReadOnlySpan<byte> glStencilMaskFunctionName => "glStencilMask"u8;
    public readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> StencilMask;
    internal static ReadOnlySpan<byte> glStencilOpFunctionName => "glStencilOp"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> StencilOp;
    internal static ReadOnlySpan<byte> glTexCoordPointerFunctionName => "glTexCoordPointer"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> TexCoordPointer;
    internal static ReadOnlySpan<byte> glTexEnviFunctionName => "glTexEnvi"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> TexEnvi;
    internal static ReadOnlySpan<byte> glTexEnvxFunctionName => "glTexEnvx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> TexEnvx;
    internal static ReadOnlySpan<byte> glTexEnvivFunctionName => "glTexEnviv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> TexEnviv;
    internal static ReadOnlySpan<byte> glTexEnvxvFunctionName => "glTexEnvxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> TexEnvxv;
    internal static ReadOnlySpan<byte> glTexImage2DFunctionName => "glTexImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> TexImage2D;
    internal static ReadOnlySpan<byte> glTexParameteriFunctionName => "glTexParameteri"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> TexParameteri;
    internal static ReadOnlySpan<byte> glTexParameterxFunctionName => "glTexParameterx"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void> TexParameterx;
    internal static ReadOnlySpan<byte> glTexParameterivFunctionName => "glTexParameteriv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> TexParameteriv;
    internal static ReadOnlySpan<byte> glTexParameterxvFunctionName => "glTexParameterxv"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void> TexParameterxv;
    internal static ReadOnlySpan<byte> glTexSubImage2DFunctionName => "glTexSubImage2D"u8;
    public readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> TexSubImage2D;
    internal static ReadOnlySpan<byte> glTranslatexFunctionName => "glTranslatex"u8;
    public readonly delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void> Translatex;
    internal static ReadOnlySpan<byte> glVertexPointerFunctionName => "glVertexPointer"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> VertexPointer;
    internal static ReadOnlySpan<byte> glViewportFunctionName => "glViewport"u8;
    public readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> Viewport;
}
