using System.Runtime.InteropServices;

namespace Rena.Interop.OpenGL;

public unsafe partial class GLES1
{
    public readonly ushort Major;
    public readonly ushort Minor;
    public readonly bool IsEmbedded;

    public readonly bool Version10;

    // Extensions

    public GLES1(LoadFunction loadFunc)
    {
        fixed (byte* name = glGetStringFunctionName)
            glGetString = (delegate* unmanaged<int, byte*>)loadFunc(name);
        if (glGetString == null) return;
        var version = glGetString(GL_VERSION);
        if (version == null) return;
        if (!TryParseVersion(MemoryMarshal.CreateReadOnlySpanFromNullTerminated(version), out Major, out Minor, out IsEmbedded)) return;

        Version10 = Major > 1 || (Major == 1 && Minor >= 0);

        if (IsEmbedded & Version10)
        {
            fixed (byte* name = glAlphaFuncFunctionName)
                glAlphaFunc = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearColorFunctionName)
                glClearColor = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearDepthfFunctionName)
                glClearDepthf = (delegate* unmanaged</* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClipPlanefFunctionName)
                glClipPlanef = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glColor4fFunctionName)
                glColor4f = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDepthRangefFunctionName)
                glDepthRangef = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFogfFunctionName)
                glFogf = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFogfvFunctionName)
                glFogfv = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFrustumfFunctionName)
                glFrustumf = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetClipPlanefFunctionName)
                glGetClipPlanef = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetFloatvFunctionName)
                glGetFloatv = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetLightfvFunctionName)
                glGetLightfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetMaterialfvFunctionName)
                glGetMaterialfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetTexEnvfvFunctionName)
                glGetTexEnvfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetTexParameterfvFunctionName)
                glGetTexParameterfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightModelfFunctionName)
                glLightModelf = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightModelfvFunctionName)
                glLightModelfv = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightfFunctionName)
                glLightf = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightfvFunctionName)
                glLightfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLineWidthFunctionName)
                glLineWidth = (delegate* unmanaged</* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLoadMatrixfFunctionName)
                glLoadMatrixf = (delegate* unmanaged</* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMaterialfFunctionName)
                glMaterialf = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMaterialfvFunctionName)
                glMaterialfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMultMatrixfFunctionName)
                glMultMatrixf = (delegate* unmanaged</* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMultiTexCoord4fFunctionName)
                glMultiTexCoord4f = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glNormal3fFunctionName)
                glNormal3f = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glOrthofFunctionName)
                glOrthof = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointParameterfFunctionName)
                glPointParameterf = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointParameterfvFunctionName)
                glPointParameterfv = (delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointSizeFunctionName)
                glPointSize = (delegate* unmanaged</* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPolygonOffsetFunctionName)
                glPolygonOffset = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glRotatefFunctionName)
                glRotatef = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glScalefFunctionName)
                glScalef = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnvfFunctionName)
                glTexEnvf = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnvfvFunctionName)
                glTexEnvfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameterfFunctionName)
                glTexParameterf = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameterfvFunctionName)
                glTexParameterfv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTranslatefFunctionName)
                glTranslatef = (delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void>)loadFunc(name);
            fixed (byte* name = glActiveTextureFunctionName)
                glActiveTexture = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glAlphaFuncxFunctionName)
                glAlphaFuncx = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glBindBufferFunctionName)
                glBindBuffer = (delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glBindTextureFunctionName)
                glBindTexture = (delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glBlendFuncFunctionName)
                glBlendFunc = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glBufferDataFunctionName)
                glBufferData = (delegate* unmanaged</* GLenum */ int, /* GLsizeiptr */ nint, /* void */ void*, /* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glBufferSubDataFunctionName)
                glBufferSubData = (delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearFunctionName)
                glClear = (delegate* unmanaged</* GLbitfield */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearColorxFunctionName)
                glClearColorx = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearDepthxFunctionName)
                glClearDepthx = (delegate* unmanaged</* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClearStencilFunctionName)
                glClearStencil = (delegate* unmanaged</* GLint */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClientActiveTextureFunctionName)
                glClientActiveTexture = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glClipPlanexFunctionName)
                glClipPlanex = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glColor4ubFunctionName)
                glColor4ub = (delegate* unmanaged</* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* GLubyte */ byte, /* void */ void>)loadFunc(name);
            fixed (byte* name = glColor4xFunctionName)
                glColor4x = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glColorMaskFunctionName)
                glColorMask = (delegate* unmanaged</* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glColorPointerFunctionName)
                glColorPointer = (delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glCompressedTexImage2DFunctionName)
                glCompressedTexImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glCompressedTexSubImage2DFunctionName)
                glCompressedTexSubImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glCopyTexImage2DFunctionName)
                glCopyTexImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glCopyTexSubImage2DFunctionName)
                glCopyTexSubImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glCullFaceFunctionName)
                glCullFace = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDeleteBuffersFunctionName)
                glDeleteBuffers = (delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDeleteTexturesFunctionName)
                glDeleteTextures = (delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDepthFuncFunctionName)
                glDepthFunc = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDepthMaskFunctionName)
                glDepthMask = (delegate* unmanaged</* GLboolean */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDepthRangexFunctionName)
                glDepthRangex = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDisableFunctionName)
                glDisable = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDisableClientStateFunctionName)
                glDisableClientState = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDrawArraysFunctionName)
                glDrawArrays = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glDrawElementsFunctionName)
                glDrawElements = (delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glEnableFunctionName)
                glEnable = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glEnableClientStateFunctionName)
                glEnableClientState = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFinishFunctionName)
                glFinish = (delegate* unmanaged</* void */ void>)loadFunc(name);
            fixed (byte* name = glFlushFunctionName)
                glFlush = (delegate* unmanaged</* void */ void>)loadFunc(name);
            fixed (byte* name = glFogxFunctionName)
                glFogx = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFogxvFunctionName)
                glFogxv = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFrontFaceFunctionName)
                glFrontFace = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glFrustumxFunctionName)
                glFrustumx = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetBooleanvFunctionName)
                glGetBooleanv = (delegate* unmanaged</* GLenum */ int, /* GLboolean */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetBufferParameterivFunctionName)
                glGetBufferParameteriv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetClipPlanexFunctionName)
                glGetClipPlanex = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGenBuffersFunctionName)
                glGenBuffers = (delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGenTexturesFunctionName)
                glGenTextures = (delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetErrorFunctionName)
                glGetError = (delegate* unmanaged</* GLenum */ int>)loadFunc(name);
            fixed (byte* name = glGetFixedvFunctionName)
                glGetFixedv = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetIntegervFunctionName)
                glGetIntegerv = (delegate* unmanaged</* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetLightxvFunctionName)
                glGetLightxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetMaterialxvFunctionName)
                glGetMaterialxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetPointervFunctionName)
                glGetPointerv = (delegate* unmanaged</* GLenum */ int, /* void */ void**, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetStringFunctionName)
                glGetString = (delegate* unmanaged</* GLenum */ int, /* GLubyte */ byte*>)loadFunc(name);
            fixed (byte* name = glGetTexEnvivFunctionName)
                glGetTexEnviv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetTexEnvxvFunctionName)
                glGetTexEnvxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetTexParameterivFunctionName)
                glGetTexParameteriv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glGetTexParameterxvFunctionName)
                glGetTexParameterxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glHintFunctionName)
                glHint = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glIsBufferFunctionName)
                glIsBuffer = (delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int>)loadFunc(name);
            fixed (byte* name = glIsEnabledFunctionName)
                glIsEnabled = (delegate* unmanaged</* GLenum */ int, /* GLboolean */ int>)loadFunc(name);
            fixed (byte* name = glIsTextureFunctionName)
                glIsTexture = (delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int>)loadFunc(name);
            fixed (byte* name = glLightModelxFunctionName)
                glLightModelx = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightModelxvFunctionName)
                glLightModelxv = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightxFunctionName)
                glLightx = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLightxvFunctionName)
                glLightxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLineWidthxFunctionName)
                glLineWidthx = (delegate* unmanaged</* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLoadIdentityFunctionName)
                glLoadIdentity = (delegate* unmanaged</* void */ void>)loadFunc(name);
            fixed (byte* name = glLoadMatrixxFunctionName)
                glLoadMatrixx = (delegate* unmanaged</* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glLogicOpFunctionName)
                glLogicOp = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMaterialxFunctionName)
                glMaterialx = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMaterialxvFunctionName)
                glMaterialxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMatrixModeFunctionName)
                glMatrixMode = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMultMatrixxFunctionName)
                glMultMatrixx = (delegate* unmanaged</* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glMultiTexCoord4xFunctionName)
                glMultiTexCoord4x = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glNormal3xFunctionName)
                glNormal3x = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glNormalPointerFunctionName)
                glNormalPointer = (delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glOrthoxFunctionName)
                glOrthox = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPixelStoreiFunctionName)
                glPixelStorei = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointParameterxFunctionName)
                glPointParameterx = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointParameterxvFunctionName)
                glPointParameterxv = (delegate* unmanaged</* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPointSizexFunctionName)
                glPointSizex = (delegate* unmanaged</* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPolygonOffsetxFunctionName)
                glPolygonOffsetx = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glPopMatrixFunctionName)
                glPopMatrix = (delegate* unmanaged</* void */ void>)loadFunc(name);
            fixed (byte* name = glPushMatrixFunctionName)
                glPushMatrix = (delegate* unmanaged</* void */ void>)loadFunc(name);
            fixed (byte* name = glReadPixelsFunctionName)
                glReadPixels = (delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glRotatexFunctionName)
                glRotatex = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glSampleCoverageFunctionName)
                glSampleCoverage = (delegate* unmanaged</* GLfloat */ float, /* GLboolean */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glSampleCoveragexFunctionName)
                glSampleCoveragex = (delegate* unmanaged</* GLclampx */ int, /* GLboolean */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glScalexFunctionName)
                glScalex = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glScissorFunctionName)
                glScissor = (delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glShadeModelFunctionName)
                glShadeModel = (delegate* unmanaged</* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glStencilFuncFunctionName)
                glStencilFunc = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLuint */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glStencilMaskFunctionName)
                glStencilMask = (delegate* unmanaged</* GLuint */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glStencilOpFunctionName)
                glStencilOp = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexCoordPointerFunctionName)
                glTexCoordPointer = (delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnviFunctionName)
                glTexEnvi = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnvxFunctionName)
                glTexEnvx = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnvivFunctionName)
                glTexEnviv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexEnvxvFunctionName)
                glTexEnvxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexImage2DFunctionName)
                glTexImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameteriFunctionName)
                glTexParameteri = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameterxFunctionName)
                glTexParameterx = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameterivFunctionName)
                glTexParameteriv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexParameterxvFunctionName)
                glTexParameterxv = (delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfixed */ uint*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTexSubImage2DFunctionName)
                glTexSubImage2D = (delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glTranslatexFunctionName)
                glTranslatex = (delegate* unmanaged</* GLfixed */ uint, /* GLfixed */ uint, /* GLfixed */ uint, /* void */ void>)loadFunc(name);
            fixed (byte* name = glVertexPointerFunctionName)
                glVertexPointer = (delegate* unmanaged</* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void>)loadFunc(name);
            fixed (byte* name = glViewportFunctionName)
                glViewport = (delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void>)loadFunc(name);
        }

    }
}
