namespace Rena.Interop.OpenGl;

public unsafe partial class Gles2
{
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glActiveShaderProgram;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glActiveTexture;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glAttachShader;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBeginQuery;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glBeginTransformFeedback;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLchar */ byte*, /* void */ void> glBindAttribLocation;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindBuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glBindBufferBase;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void> glBindBufferRange;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindFramebuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLint */ int, /* GLboolean */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glBindImageTexture;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glBindProgramPipeline;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindRenderbuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glBindSampler;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindTexture;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glBindTransformFeedback;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glBindVertexArray;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLintptr */ nint, /* GLsizei */ int, /* void */ void> glBindVertexBuffer;
    private readonly delegate* unmanaged</* void */ void> glBlendBarrier;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glBlendColor;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glBlendEquation;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendEquationSeparate;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendEquationSeparatei;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* void */ void> glBlendEquationi;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendFunc;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendFuncSeparate;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendFuncSeparatei;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLenum */ int, /* void */ void> glBlendFunci;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLbitfield */ int, /* GLenum */ int, /* void */ void> glBlitFramebuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizeiptr */ nint, /* void */ void*, /* GLenum */ int, /* void */ void> glBufferData;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void*, /* void */ void> glBufferSubData;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int> glCheckFramebufferStatus;
    private readonly delegate* unmanaged</* GLbitfield */ int, /* void */ void> glClear;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLfloat */ float, /* GLint */ int, /* void */ void> glClearBufferfi;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLfloat */ float*, /* void */ void> glClearBufferfv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int*, /* void */ void> glClearBufferiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLuint */ uint*, /* void */ void> glClearBufferuiv;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glClearColor;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glClearDepthf;
    private readonly delegate* unmanaged</* GLint */ int, /* void */ void> glClearStencil;
    private readonly delegate* unmanaged</* GLsync */ void*, /* GLbitfield */ int, /* GLuint64 */ ulong, /* GLenum */ int> glClientWaitSync;
    private readonly delegate* unmanaged</* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* void */ void> glColorMask;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* GLboolean */ int, /* void */ void> glColorMaski;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glCompileShader;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexImage3D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexSubImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glCompressedTexSubImage3D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLintptr */ nint, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void> glCopyBufferSubData;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLuint */ uint, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glCopyImageSubData;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* void */ void> glCopyTexImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glCopyTexSubImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glCopyTexSubImage3D;
    private readonly delegate* unmanaged</* GLuint */ uint> glCreateProgram;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint> glCreateShader;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLchar */ byte*, /* GLuint */ uint> glCreateShaderProgramv;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glCullFace;
    private readonly delegate* unmanaged</* GLDEBUGPROC */ delegate* unmanaged<int, int, uint, int, nint, sbyte*, void*, void>, /* void */ void*, /* void */ void> glDebugMessageCallback;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLsizei */ int, /* GLuint */ uint*, /* GLboolean */ int, /* void */ void> glDebugMessageControl;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* GLenum */ int, /* GLsizei */ int, /* GLchar */ byte*, /* void */ void> glDebugMessageInsert;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteBuffers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteFramebuffers;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glDeleteProgram;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteProgramPipelines;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteQueries;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteRenderbuffers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteSamplers;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glDeleteShader;
    private readonly delegate* unmanaged</* GLsync */ void*, /* void */ void> glDeleteSync;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteTextures;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteTransformFeedbacks;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glDeleteVertexArrays;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glDepthFunc;
    private readonly delegate* unmanaged</* GLboolean */ int, /* void */ void> glDepthMask;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> glDepthRangef;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glDetachShader;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glDisable;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glDisableVertexAttribArray;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glDisablei;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glDispatchCompute;
    private readonly delegate* unmanaged</* GLintptr */ nint, /* void */ void> glDispatchComputeIndirect;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLsizei */ int, /* void */ void> glDrawArrays;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void*, /* void */ void> glDrawArraysIndirect;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glDrawArraysInstanced;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLenum */ int*, /* void */ void> glDrawBuffers;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glDrawElements;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* GLint */ int, /* void */ void> glDrawElementsBaseVertex;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glDrawElementsIndirect;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* GLsizei */ int, /* void */ void> glDrawElementsInstanced;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* GLsizei */ int, /* GLint */ int, /* void */ void> glDrawElementsInstancedBaseVertex;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glDrawRangeElements;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLenum */ int, /* void */ void*, /* GLint */ int, /* void */ void> glDrawRangeElementsBaseVertex;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glEnable;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glEnableVertexAttribArray;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glEnablei;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glEndQuery;
    private readonly delegate* unmanaged</* void */ void> glEndTransformFeedback;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLbitfield */ int, /* GLsync */ void*> glFenceSync;
    private readonly delegate* unmanaged</* void */ void> glFinish;
    private readonly delegate* unmanaged</* void */ void> glFlush;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void> glFlushMappedBufferRange;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> glFramebufferParameteri;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* void */ void> glFramebufferRenderbuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* GLint */ int, /* void */ void> glFramebufferTexture;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* GLint */ int, /* void */ void> glFramebufferTexture2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* void */ void> glFramebufferTextureLayer;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glFrontFace;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenBuffers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenFramebuffers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenProgramPipelines;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenQueries;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenRenderbuffers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenSamplers;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenTextures;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenTransformFeedbacks;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGenVertexArrays;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glGenerateMipmap;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLint */ int*, /* GLenum */ int*, /* GLchar */ byte*, /* void */ void> glGetActiveAttrib;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLint */ int*, /* GLenum */ int*, /* GLchar */ byte*, /* void */ void> glGetActiveUniform;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetActiveUniformBlockName;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetActiveUniformBlockiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLuint */ uint*, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetActiveUniformsiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLuint */ uint*, /* void */ void> glGetAttachedShaders;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLchar */ byte*, /* GLint */ int> glGetAttribLocation;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLboolean */ int*, /* void */ void> glGetBooleani_v;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int*, /* void */ void> glGetBooleanv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint64 */ long*, /* void */ void> glGetBufferParameteri64v;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetBufferParameteriv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void**, /* void */ void> glGetBufferPointerv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLenum */ int*, /* GLenum */ int*, /* GLuint */ uint*, /* GLenum */ int*, /* GLsizei */ int*, /* GLchar */ byte*, /* GLuint */ uint> glGetDebugMessageLog;
    private readonly delegate* unmanaged</* GLenum */ int> glGetError;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetFloatv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLchar */ byte*, /* GLint */ int> glGetFragDataLocation;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetFramebufferAttachmentParameteriv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetFramebufferParameteriv;
    private readonly delegate* unmanaged</* GLenum */ int> glGetGraphicsResetStatus;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLint64 */ long*, /* void */ void> glGetInteger64i_v;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint64 */ long*, /* void */ void> glGetInteger64v;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLint */ int*, /* void */ void> glGetIntegeri_v;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int*, /* void */ void> glGetIntegerv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glGetInternalformativ;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLfloat */ float*, /* void */ void> glGetMultisamplefv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetObjectLabel;
    private readonly delegate* unmanaged</* void */ void*, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetObjectPtrLabel;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void**, /* void */ void> glGetPointerv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLenum */ int*, /* void */ void*, /* void */ void> glGetProgramBinary;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetProgramInfoLog;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetProgramInterfaceiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetProgramPipelineInfoLog;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetProgramPipelineiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLchar */ byte*, /* GLuint */ uint> glGetProgramResourceIndex;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLchar */ byte*, /* GLint */ int> glGetProgramResourceLocation;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetProgramResourceName;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint, /* GLsizei */ int, /* GLenum */ int*, /* GLsizei */ int, /* GLsizei */ int*, /* GLint */ int*, /* void */ void> glGetProgramResourceiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetProgramiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glGetQueryObjectuiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetQueryiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetRenderbufferParameteriv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetSamplerParameterIiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glGetSamplerParameterIuiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetSamplerParameterfv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetSamplerParameteriv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetShaderInfoLog;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* GLint */ int*, /* void */ void> glGetShaderPrecisionFormat;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLchar */ byte*, /* void */ void> glGetShaderSource;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetShaderiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLubyte */ byte*> glGetString;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLubyte */ byte*> glGetStringi;
    private readonly delegate* unmanaged</* GLsync */ void*, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int*, /* GLint */ int*, /* void */ void> glGetSynciv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetTexLevelParameterfv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetTexLevelParameteriv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetTexParameterIiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glGetTexParameterIuiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetTexParameterfv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetTexParameteriv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLsizei */ int, /* GLsizei */ int*, /* GLsizei */ int*, /* GLenum */ int*, /* GLchar */ byte*, /* void */ void> glGetTransformFeedbackVarying;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLchar */ byte*, /* GLuint */ uint> glGetUniformBlockIndex;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLchar */ byte*, /* GLuint */ uint*, /* void */ void> glGetUniformIndices;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLchar */ byte*, /* GLint */ int> glGetUniformLocation;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLfloat */ float*, /* void */ void> glGetUniformfv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int*, /* void */ void> glGetUniformiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLuint */ uint*, /* void */ void> glGetUniformuiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetVertexAttribIiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glGetVertexAttribIuiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* void */ void**, /* void */ void> glGetVertexAttribPointerv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glGetVertexAttribfv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glGetVertexAttribiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glGetnUniformfv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glGetnUniformiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glGetnUniformuiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* void */ void> glHint;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int*, /* void */ void> glInvalidateFramebuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int*, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glInvalidateSubFramebuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsBuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int> glIsEnabled;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLboolean */ int> glIsEnabledi;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsFramebuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsProgram;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsProgramPipeline;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsQuery;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsRenderbuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsSampler;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsShader;
    private readonly delegate* unmanaged</* GLsync */ void*, /* GLboolean */ int> glIsSync;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsTexture;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsTransformFeedback;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLboolean */ int> glIsVertexArray;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glLineWidth;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glLinkProgram;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* GLbitfield */ int, /* void */ void*> glMapBufferRange;
    private readonly delegate* unmanaged</* GLbitfield */ int, /* void */ void> glMemoryBarrier;
    private readonly delegate* unmanaged</* GLbitfield */ int, /* void */ void> glMemoryBarrierByRegion;
    private readonly delegate* unmanaged</* GLfloat */ float, /* void */ void> glMinSampleShading;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLsizei */ int, /* GLchar */ byte*, /* void */ void> glObjectLabel;
    private readonly delegate* unmanaged</* void */ void*, /* GLsizei */ int, /* GLchar */ byte*, /* void */ void> glObjectPtrLabel;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* void */ void> glPatchParameteri;
    private readonly delegate* unmanaged</* void */ void> glPauseTransformFeedback;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* void */ void> glPixelStorei;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* void */ void> glPolygonOffset;
    private readonly delegate* unmanaged</* void */ void> glPopDebugGroup;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glPrimitiveBoundingBox;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* void */ void*, /* GLsizei */ int, /* void */ void> glProgramBinary;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int, /* void */ void> glProgramParameteri;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLfloat */ float, /* void */ void> glProgramUniform1f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glProgramUniform1fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* void */ void> glProgramUniform1i;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glProgramUniform1iv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLuint */ uint, /* void */ void> glProgramUniform1ui;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glProgramUniform1uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glProgramUniform2f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glProgramUniform2fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glProgramUniform2i;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glProgramUniform2iv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glProgramUniform2ui;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glProgramUniform2uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glProgramUniform3f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glProgramUniform3fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glProgramUniform3i;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glProgramUniform3iv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glProgramUniform3ui;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glProgramUniform3uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glProgramUniform4f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glProgramUniform4fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glProgramUniform4i;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glProgramUniform4iv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glProgramUniform4ui;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glProgramUniform4uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix2fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix2x3fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix2x4fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix3fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix3x2fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix3x4fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix4fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix4x2fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glProgramUniformMatrix4x3fv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* GLsizei */ int, /* GLchar */ byte*, /* void */ void> glPushDebugGroup;
    private readonly delegate* unmanaged</* GLenum */ int, /* void */ void> glReadBuffer;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glReadPixels;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glReadnPixels;
    private readonly delegate* unmanaged</* void */ void> glReleaseShaderCompiler;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glRenderbufferStorage;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glRenderbufferStorageMultisample;
    private readonly delegate* unmanaged</* void */ void> glResumeTransformFeedback;
    private readonly delegate* unmanaged</* GLfloat */ float, /* GLboolean */ int, /* void */ void> glSampleCoverage;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLbitfield */ int, /* void */ void> glSampleMaski;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glSamplerParameterIiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glSamplerParameterIuiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glSamplerParameterf;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glSamplerParameterfv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int, /* void */ void> glSamplerParameteri;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLenum */ int, /* GLint */ int*, /* void */ void> glSamplerParameteriv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glScissor;
    private readonly delegate* unmanaged</* GLsizei */ int, /* GLuint */ uint*, /* GLenum */ int, /* void */ void*, /* GLsizei */ int, /* void */ void> glShaderBinary;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLchar */ byte*, /* GLint */ int*, /* void */ void> glShaderSource;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLuint */ uint, /* void */ void> glStencilFunc;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* GLuint */ uint, /* void */ void> glStencilFuncSeparate;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glStencilMask;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLuint */ uint, /* void */ void> glStencilMaskSeparate;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glStencilOp;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void> glStencilOpSeparate;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* void */ void> glTexBuffer;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint, /* GLintptr */ nint, /* GLsizeiptr */ nint, /* void */ void> glTexBufferRange;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLint */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexImage3D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glTexParameterIiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLuint */ uint*, /* void */ void> glTexParameterIuiv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float, /* void */ void> glTexParameterf;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLfloat */ float*, /* void */ void> glTexParameterfv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int, /* void */ void> glTexParameteri;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLenum */ int, /* GLint */ int*, /* void */ void> glTexParameteriv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glTexStorage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLboolean */ int, /* void */ void> glTexStorage2DMultisample;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glTexStorage3D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLsizei */ int, /* GLenum */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLboolean */ int, /* void */ void> glTexStorage3DMultisample;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexSubImage2D;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLsizei */ int, /* GLenum */ int, /* GLenum */ int, /* void */ void*, /* void */ void> glTexSubImage3D;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLsizei */ int, /* GLchar */ byte*, /* GLenum */ int, /* void */ void> glTransformFeedbackVaryings;
    private readonly delegate* unmanaged</* GLint */ int, /* GLfloat */ float, /* void */ void> glUniform1f;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glUniform1fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* void */ void> glUniform1i;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glUniform1iv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLuint */ uint, /* void */ void> glUniform1ui;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glUniform1uiv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glUniform2f;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glUniform2fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glUniform2i;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glUniform2iv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glUniform2ui;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glUniform2uiv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glUniform3f;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glUniform3fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glUniform3i;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glUniform3iv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glUniform3ui;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glUniform3uiv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glUniform4f;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLfloat */ float*, /* void */ void> glUniform4fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glUniform4i;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLint */ int*, /* void */ void> glUniform4iv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glUniform4ui;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLuint */ uint*, /* void */ void> glUniform4uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glUniformBlockBinding;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix2fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix2x3fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix2x4fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix3fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix3x2fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix3x4fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix4fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix4x2fv;
    private readonly delegate* unmanaged</* GLint */ int, /* GLsizei */ int, /* GLboolean */ int, /* GLfloat */ float*, /* void */ void> glUniformMatrix4x3fv;
    private readonly delegate* unmanaged</* GLenum */ int, /* GLboolean */ int> glUnmapBuffer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glUseProgram;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLbitfield */ int, /* GLuint */ uint, /* void */ void> glUseProgramStages;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glValidateProgram;
    private readonly delegate* unmanaged</* GLuint */ uint, /* void */ void> glValidateProgramPipeline;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float, /* void */ void> glVertexAttrib1f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float*, /* void */ void> glVertexAttrib1fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glVertexAttrib2f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float*, /* void */ void> glVertexAttrib2fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glVertexAttrib3f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float*, /* void */ void> glVertexAttrib3fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* GLfloat */ float, /* void */ void> glVertexAttrib4f;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLfloat */ float*, /* void */ void> glVertexAttrib4fv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glVertexAttribBinding;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glVertexAttribDivisor;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLenum */ int, /* GLboolean */ int, /* GLuint */ uint, /* void */ void> glVertexAttribFormat;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* GLint */ int, /* void */ void> glVertexAttribI4i;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int*, /* void */ void> glVertexAttribI4iv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* GLuint */ uint, /* void */ void> glVertexAttribI4ui;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint*, /* void */ void> glVertexAttribI4uiv;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLenum */ int, /* GLuint */ uint, /* void */ void> glVertexAttribIFormat;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLenum */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glVertexAttribIPointer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLint */ int, /* GLenum */ int, /* GLboolean */ int, /* GLsizei */ int, /* void */ void*, /* void */ void> glVertexAttribPointer;
    private readonly delegate* unmanaged</* GLuint */ uint, /* GLuint */ uint, /* void */ void> glVertexBindingDivisor;
    private readonly delegate* unmanaged</* GLint */ int, /* GLint */ int, /* GLsizei */ int, /* GLsizei */ int, /* void */ void> glViewport;
    private readonly delegate* unmanaged</* GLsync */ void*, /* GLbitfield */ int, /* GLuint64 */ ulong, /* void */ void> glWaitSync;
}
